### ISSUE TITLE
Some lscpu flags need an alias

### ISSUE THREAD

**Issue by alexKrauseTUD** [db-tu-dresden/TSL#101]
When the TSL is generated, the required compiler arguments are derived from the lscpu list; either trhough py-cpuinfo or lscpu.

However, some flags have no direct mapping to compiler flags, especially avx512 flags, e.g.
| lscpu | g++/clang |
| --- | --- |
| avx512_fp16 | -mavx512fp16|
| avx512_vpopcntdq | -mavx512vpopcntdq |
| avx512_vbmi2 | -mavx512vbmi2 |

Maybe we can conventionally just remove the underscores, but this might not be true for all flags.

**Comment by JPietrzykTUD** [comment]
Fixed with #103
