### ISSUE TITLE
Different requirement for test cases lead to multiple definitions of the same test case

### ISSUE THREAD

**Issue by JPietrzykTUD** [db-tu-dresden/TSL#31]
If the requirements differ for multiple tests of primitive, multiple test cases are generated (with the same test identifier).

**Comment by alexKrauseTUD** [comment]
I tried replicating this issue based on https://github.com/DerTuchi/TVLGen/commit/6bf7c99fb9e4aa20257e13d85c9cc8a63dfec9a4. However, when I moved the specific yaml file to an up-to-date version of the current generator, the duplication error did not persist. Can someone else replicate the problem one a clean state?

**Comment by alexKrauseTUD** [comment]
Solved with PR #45.
