### ISSUE TITLE
Shift do not supported for `uint8_t`

### ISSUE THREAD

**Issue by lawben** [db-tu-dresden/TSL#99]
It looks like there is currently no support for shifts of `uint8_t` in AVX512 vectors.

**Comment by lawben** [comment]
Also applies to 16 byte SSE vectors.

```
error: no member named 'apply' in 'tsl::functors::shift_right<tsl::simd<unsigned char, tsl::sse, 16>, true, tsl::workaround>'
```

**Comment by lawben** [comment]
Other SSE 16 byte functions missing for `uint8_t:
- `load`:
`error: no member named 'apply' in 'tsl::functors::load<tsl::simd<unsigned char, tsl::sse, 16>, tsl::workaround>'`

- `set1`: `error: no member named 'apply' in 'tsl::functors::set1<tsl::simd<unsigned char, tsl::sse, 16>, tsl::workaround>'`
- `shift_right_vector`: `error: no member named 'apply' in 'tsl::functors::shift_right_vector<tsl::simd<unsigned char, tsl::sse, 16>, true, tsl::workaround>'`

**Comment by lawben** [comment]
Sorry for the edit spam. I messed up something and then suddenly a lot of things did not work anymore... My bad. It looks like only the `uint8_t` shifts are an issue, but also for SSE and AVX2, not just AVX512.

**Comment by JPietrzykTUD** [comment]
Added support for right and left shifts for 8 and 16-bit integers for Intel with #103 
Unfortunately, I didn't find a clever way to realize an 8 / 16-bit arithmetic right shift for SSE (without AVX instructions) that operates on two vectors.
